language: perl
perl:
- '5.18'
- '5.16'
- '5.14'
- '5.12'
- '5.10'
- '5.8'

env:
  - secure: "WicSuk4zLYzgiFbBXKQ7BviLI3iptwPE24uCXmNR8u1H6LtT/HLO5KyhYsNZfnt5qYGdByQDenoy/Ts1uibmJk/oM/nVTJpM5VH4pxcG3D9OTlPH8ZvHnNmUak7eHqkO0On/0SKjm1GwQRtTpixi4wxmFr0Nl34tK+7LjlcsB7erz8neDdULlC2/VALNZd/vMQkZPlOHUrqhw9GRl1gqygjPtgv73G+vGzdcckTRaw+ITjMM801iWipiseUOm7OwpxIEQErwnTS0Xyp+YVAm8f8E3DPcyLi65OYSznUVIa+ZfRP/Xh+upNtRUY22SnwsjVib7zvflOUsVGTCItj13EmRzq1rmN+IqRlvY8SKar+MoVtzTS0raEYx+uQq/5IC/Kwb79qW745XQ62EpYt9dXmwtT2NMT9a2gJXXkeg70lJqE0Bh5xXYqZKH0fh9UDD81kPCo1iHHQDXctwNnR6X2G0a6hxkQQmBDY/jGlqL6nD3/NWFQqvn333en50oQ5SqOY7FM7BDaFraJKTtKPniEqNuwWUn+RTlBmFra2HPMpteBfBaWHyJMyj7RgnrLe9V6O5feuAGV2qtOLbe42WLHl658y6qv5oCVkvWhcNuTZJm2b4E+3WwZywSmC8aVte9kglO2YzUO1IDOG1Qi+u4rq4GVY3r/xAmuX7KocWyko="
  - secure: "kwm8A7sShzhi0Uq8RqRi3e23p5/Ihmwt/Z77l7v5HVrlSJyZbcfrrTGpZhN1VYzabnGyU0hyF1rkDIEDadgX8orf3BWN9GUzx9x3SOatTSz4UVidGqW5rGlmmY/BptQ16A4tSYS9l9onEC8MhsI6CeLhKV0rHw7YrmuZzscuYox/mKBXnzoGW15iea5Ew2iC3jbEmdakX2pdWmYHGGagptRIOJurhfDC5gTKiHWnXUvzvWYCiznl8l33zA4zIDXR5L2hegLVIUFJR51yWZrfFc60xYSK3WdeJiGARDcZR3JOO3TnzISgxFCxwrmry8ezFNUlgIfnDYO05SeOPfO+K/1kDg52QIPI7Duzp5kutg9hbl0IkbHR0geh0llh/eWLGlETlNM46x+n+LcEL0umXiKUpTHCfOhY7w7v4+0bGMNvnTLGuggyW5K3SjSjc2pfEd6eGmD2DtvarVQlLRPL9PRdXE6AfP99zRK5aUjE3pvMbeFSKU+3DIcb+5DYNSuly3liOgVeEunZrwxoKbLakZMQfVuDfW/qp2F97TyPd41jqAcyVk6lYugINYdPwd5vYunelyOzxNI7514NVk9raS2iqnKIN2S6+y1z5CKzuB77VyQ8X+iUfJlImO3kttlC3Yx3xDnmgVx5PC92PuAyHbloXQv9vL3tLEttlGl/9+s="
 - RELEASE_TESTING=1
 - AUTHOR_TESTING=1

install:
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
   - cpanm --quiet --notest Devel::Cover::Report::Coveralls
   - cpanm --quiet --notest --installdeps .

script:
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -Ilib -lrsv t
   - cover

after_success:
   - cover -report coveralls



